CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE todos (
  id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
  title VARCHAR NOT NULL,
  body TEXT,
  published BOOLEAN NOT NULL DEFAULT 'f'
)
