[package]
name = "jsonapi-derive"
version = "0.1.0"
authors = ["Blake Pettersson <blake.pettersson@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
jsonapi = { path = "../jsonapi" }
serde = "0.8"
serde_derive = "0.8"
syn = "0.11"
quote = "0.3"
Inflector = "*"